coveo/vsforce

- src/symbols/visualforceComponentCache.ts
- src/symbols/visualforceComponentFetcher.ts
- src/symbols/visualforceComponentFetcherBase.ts
- src/symbols/visualforceComponentFetcherFile.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/vsforce.ts
> Added disposable to VisualforceComponentCache and fetcher file watcher

- .travis.yml
> New travis file

- package.json
- src/providers/salesforceContentProvider.ts
- src/providers/visualforceCompletionItemProvider.ts
- src/providers/visualforceDefinitionProvider.ts
- src/providers/visualforceWorkspaceSymbolProvider.ts
- src/symbols/visualforceComponent.ts
- src/symbols/visualforceComponentFetcherBase.ts
- src/symbols/visualforceComponentFetcherFile.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/vsforce.ts
- typings/htmlparser2/htmlparser2.d.ts
> New VisualforceDefinitionProvider and VisualforceSymbolProvider

- package.json
> chore(package): update pretty-typescript to version 1.12.1

- package.json
**Fixes issue:** #
https://greenkeeper.io/
> chore(package): update vscode to version 0.11.14

- package.json
- src/commands/command.ts
- src/commands/showDiffCommand.ts
- src/commands/showLogsCommand.ts
- src/connection.ts
- src/providers/salesforceContentProvider.ts
- src/providers/visualforceCompletionItemProvider.ts
- src/symbols/visualforceComponentFetcherBase.ts
- src/symbols/visualforceComponentFetcherFile.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils.ts
- src/vsforce.ts
**Fixes issue:** #11 
provides a context menu to do a diff with the local versus the salesforce
> feature(diff): Diff with salesforce

- src/providers/salesforceContentProvider.ts
> adds a status bar item for the diff (salesforce) mode

- src/commands/showDiffCommand.ts
> change diff message

- package.json
- src/commands/retrieveCommand.ts
- src/connection.ts
- src/utils.ts
- src/vsforce.ts
> Added retrieve package function

- package.json
**Fixes issue:** #
https://greenkeeper.io/
> chore(package): update vscode to version 0.11.15

- package.json
**Fixes issue:** #
https://greenkeeper.io/
> chore(package): update pretty-typescript to version 1.13.0

- package.json
- src/commands/command.ts
- src/commands/retrieveCommand.ts
- src/commands/showDiffCommand.ts
- src/commands/showLogsCommand.ts
- src/connection.ts
- src/providers/apexCompletionItemProvider.ts
- src/providers/salesforceContentProvider.ts
- src/providers/visualforceWorkspaceSymbolProvider.ts
- src/symbols/apexObject.ts
- src/symbols/apexObjectTreeCache.ts
- src/symbols/visualforceBaseComponents.ts
- src/symbols/visualforceComponent.ts
- src/symbols/visualforceComponentCache.ts
- src/symbols/visualforceComponentFetcher.ts
- src/symbols/visualforceComponentFetcherBase.ts
- src/symbols/visualforceComponentFetcherFile.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils.ts
- src/vsforce.ts
- tslint.json
Fixes a lot of issues with tslint
> tslint fixes

- src/builder/salesforceQueryBuilder.ts
- src/commands/showDiffCommand.ts
> add a new layer for salesforce component queries

- src/builder/soqlObject.ts
- src/builder/soqlQueryBuilder.ts
- src/commands/showDiffCommand.ts
> SOQL query builder

- src/commands/showLogsCommand.ts
- src/connection.ts
- src/extension.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils.ts
> refactor code + SOQL + Salesforce builder

- package.json
- src/commands/showDiffCommand.ts
- src/commands/soqlCommand.ts
- src/vsforce.ts
> SOQL query

- package.json
> chore(package): update cz-conventional-changelog to version 1.2.0

- src/builder/salesforceQueryBuilder.ts
- src/commands/showDiffCommand.ts
instead of using require now uses the right syntax the right way
> style(vscode import): change how to import vscode

- package.json
- src/builder/salesforceQueryBuilder.ts
- src/builder/soqlObject.ts
- src/builder/soqlQueryBuilder.ts
- src/commands/showLogsCommand.ts
- src/commands/soqlCommand.ts
- src/connection.ts
- src/providers/salesforceContentProvider.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils.ts
- tslint.json
Fix vscode dependency version.
Fix some logic with the builders
Fix command name prefix
Add tsling configuration
> revert vscode dependency

- src/utils/config.ts
> loginUrl is optionnal

- .vscode/launch.json
- .vscode/tasks.json
> New build task settings

- package.json
> removed non working commands

- src/commands/showDiffCommand.ts
- src/commands/soqlCommand.ts
> misc fixes

- src/commands/pushFileToSalesforceCommand.ts
- src/connection.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils/utils.ts
- src/vsforce.ts
> fix uppercase refs

- src/builder/soqlObject.ts
- src/commands/deploypackageCommand.ts
- src/commands/pushFileToSalesforceCommand.ts
- src/commands/retrieveCommand.ts
- src/commands/showDiffCommand.ts
- src/commands/soqlCommand.ts
- src/connection.ts
- src/providers/salesforceContentProvider.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils/config.ts
- src/utils/statusBarUtil.ts
- src/utils/utils.ts
- src/vsforce.ts
> clean up formatting, refactor soql query builder

- src/commands/deploypackageCommand.ts
- src/commands/retrieveCommand.ts
with the deploy/retrieve commands
> Updated the handling of the status bar

- src/commands/deploypackageCommand.ts
- src/commands/retrieveCommand.ts
- src/utils/utils.ts
> Fix for when you dont select a package.xml

- README.md
> marketplace badges maybe ?

- README.md
> Pimp up the README.md file somewhat.

- README.md
- src/commands/pushFileToSalesforceCommand.ts
- src/connection.ts
- src/symbols/visualforceComponentFetcherSalesforce.ts
- src/utils/config.ts
- src/utils/utils.ts
- src/vsforce.ts
Fixed the config singleton,
user Config.getInstance() now.
+ Removed obligatory param security Token
> Fixed the singleton config

- src/utils/config.ts
> Fix a bug when there is no security token in the config

- src/commands/deployPackageCommand.ts
- src/commands/retrieveCommand.ts
Added a timestamp to deploy/retrieve commands
**Fixes issue:** #96
> Added a timestamp to deploy/retrieve commands
